[package]
name = "sfind"
version = "0.1.1"
edition = "2024"
description = "Simple, fast and efficient substring find tool for the command line."
license = "MIT"

[dependencies]
clap = { version = "4.5.50", features = ["cargo"] }
walkdir = "2.5.0"
colored = "3.0.0"
rayon = "1.11.0"
memchr = "2.7.6"
